
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-4pm-5
owner: ucsb-cs156-s24
repo_name: team02-s24-4pm-5
pull_requests: [{"author":{"id":"U_kgDOBdHhNQ","is_bot":false,"login":"GarvinYoung","name":""},"headRefName":"GY-Articles-Put","number":60,"title":"Created PUT Method for Articles","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-5/pull/60"},{"author":{"id":"U_kgDOBdHhNQ","is_bot":false,"login":"GarvinYoung","name":""},"headRefName":"GY-Articles-Delete","number":59,"title":"Created DELETE Method for Articles","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-5/pull/59"}]
