
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-4pm-5
owner: ucsb-cs156-s24
repo_name: team02-s24-4pm-5
pull_requests: [{"author":{"id":"U_kgDOBnFWjw","is_bot":false,"login":"Baimin-Wang","name":""},"headRefName":"BW-UCSBDiningCommonsMenuItem-Get","number":63,"title":"Created GET method for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-5/pull/63"},{"author":{"id":"U_kgDOBckqqw","is_bot":false,"login":"CongruiDu","name":"RayDu"},"headRefName":"RD-Organization-db","number":62,"title":"Create Database Table for UCSB Organization","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-5/pull/62"},{"author":{"id":"U_kgDOBnFWjw","is_bot":false,"login":"Baimin-Wang","name":""},"headRefName":"BW-UCSBDinningCommonMenuItem-create-db","number":61,"title":"Create Database Table for UCSB Dinning Commons Menu Item","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-5/pull/61"}]
